import { StyleSheet, Text, View ,Image, TouchableOpacity} from 'react-native'
import React from 'react'
import AiText from './AiText';
import video from '../assets/images/video.png';
const VideoCard = (props) => {
  return (
    <TouchableOpacity className="gap-[8px] mb-[16px] w-[100%]" style={styles.container} onPress={props.onPress}> 
      <Image 
      className="w-[144px] h-[92px] rounded-[8px]"
      source={{ uri: props.source }}
       style={styles.img} />
      <View style={{width:'50%'}}>
        <AiText title='Generated by AI'/>
        <Text style={[styles.des,styles.font]} className="w-[176px] mt-[6px] text-[14px] font-[500] leading-[20px] text-left">{props.title}</Text>
      </View>
    </TouchableOpacity>
  )
}

export default VideoCard

const styles = StyleSheet.create({
  font:{
    fontFamily: 'Helvetica Neue',
  },
    container:{
        flexDirection:'row',
        width:'100%',
        // alignItems:'center',
        // gap:8,
        // marginBottom:15,
        // alignSelf:'flex-start',
    },
    img:{
        // width:160,
        // height:100,
        // borderRadius:12,
        resizeMode:'stretch',
    },
    des:{
        color:'#1A2233',
        // fontSize:16,
        // fontWeight:'500',
        // width:176,
    }
})